### PR TITLE
Fix property access in production and turn on prod testing

### LINKED ISSUE #1371: Native property access doesn’t work in production
When running m3 in a production build using native properties doesn’t work, as `megamorphicModelProxyHandler` isn’t defined, and the proxy constructor throws an error. It’s only defined inside an `if (DEBUG)` statement, making it work fine in development builds. 

Would it be sufficient to move the declaration outside of that if statement, or is there a reason it’s inside it?

Code ref: https://github.com/hjdivad/ember-m3/blob/master/addon/model.js#L115

### PR DESCRIPTION
**Pull request by igorT**
Fixes #1371

### CODE REVIEW

File: addon/model.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ if (CUSTOM_MODEL_CLASS) {
       // have to use it. This is safe, because we already checked that the
       // property is not `in` the instance, so it will definitely call
       // `unknownProperty` and will not re-enter.
-      return receiver.get(key);
+      return target.get(key);
```
Comment (hjdivad) [inline addon/model.js:94]: 1. comment is now out of date
2. there's some trickiness here, the comment should explain
  i. why we're using `target` instead of `receiver`, since it's non-obvious without knowing the `Ember.get` implementation
  ii. what trade-off is (i.e. that `this` will not be the proxy in `unknownProperty` which is something we only need to be aware of within `ember-m3` but not something that will impact users)

File: tests/unit/model/native-access-test.js [hunk 2]
```diff
@@ -122,124 +123,135 @@ if (CUSTOM_MODEL_CLASS && HAS_NATIVE_PROXY) {
...
+        let book = this.store.peekRecord('com.example.bookstore.Book', 'urn:li:book:1');
 
-      assert.equal(
-        book.title,
-        'How to Win Friends and Influence People',
-        'accessed field via native property get'
-      );
+        assert.expectDeprecation(() => {
+          book.name = 'Temp title';
+        }, `You set the property 'name' on a 'com.example.bookstore.book' with id 'urn:li:book:1'`);
```
Comment (hjdivad) [inline tests/unit/model/native-access-test.js:173]: why don't we `if(DEBUG)` this assertion rather than the whole test?  the bulk of  the test still seems relevant in prod mode or am i missing something?

**Review by hjdivad — COMMENTED** [review]
LGTM, only real complaint is let's update the comment in the proxy as the code is a little tricky and it depends on particular details of `Ember.get`

File: tests/unit/model/native-access-test.js (hunk 2 above)
Comment (igorT) [reply tests/unit/model/native-access-test.js:173]: Yeah good point, we would still want it to work in prod and I'm not sure we have a different test for it. I'll rename the test as well, I added the guard because the name suggested it was asserting the deprecation

File: addon/model.js (hunk 1 above)
Comment (igorT) [reply addon/model.js:102]: Fixed

File: tests/unit/model/native-access-test.js (hunk 2 above)
Comment (igorT) [reply tests/unit/model/native-access-test.js:173]: Done

**Review by hjdivad — APPROVED** [review]
LGTM please combine the commits before merging so we have clean commit history
